name: Lint, Tests, Deploy
on:
  push:
    branches:
      - dev

jobs:
  check_format_and_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with: 
            node-version: '20'

      - name: Set up Python 3.11
        uses: actions/setup-python@v4  
        with:
          python-version: '3.11'

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin

      - name: Set up Spark 3.4.1
        uses: vemonet/setup-spark@v1
        with:
          spark-version: '3.4.1'
          hadoop-version: '3'

      - name: Install Poetry and dependencies
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true  # Enable virtual environment creation for isolation
          virtualenvs-in-project: true  # Store virtual environment within the project
        
      - name: install poetry  
        run: |
          make install

      - name: Lint and format code
        run: |
          make lint
          make format

      - name: Run unit tests with PySpark
        run: |
          make test

      - name: Check Spark version 
        run: |
          spark-submit --version

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  

      - uses: databricks/setup-cli@main

      - run: make deploy_dev
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
 