name: Deploy to prod 

on: 
  push:
    branches:
      - main 

jobs: 
  deploy: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: databricks/setup-cli@main

      - run: databricks bundle deploy --target prod
        env: 
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN}}
          
  